- name: dependabot[bot]
  email: 49699333+dependabot[bot]@users.noreply.github.com
  github: dependabot[bot]
  num_commits: 11
  first_commit: 2026-04-23 13:10:39
- name: pre-commit-ci[bot]
  email: 66853113+pre-commit-ci[bot]@users.noreply.github.com
  github: pre-commit-ci[bot]
  num_commits: 6
  first_commit: 2025-01-29 02:19:36
- name: Dan Yeaw
  email: dan@yeaw.me
  github: danyeaw
  num_commits: 4
  first_commit: 2026-06-15 23:09:55
- name: Jannis Leidel
  email: jannis@leidel.info
  github: jezdez
  num_commits: 42
  first_commit: 2026-04-22 23:16:58
- name: conda-bot
  email: 18747875+conda-bot@users.noreply.github.com
  github: conda-bot
  num_commits: 9
  first_commit: 2026-06-15 20:10:30
- name: jaimergp
  email: jaimergp@users.noreply.github.com
  github: jaimergp
  num_commits: 21
  first_commit: 2025-01-11 20:00:29
